# Postgres configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:29092}

  # JPA configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        enable_lazy_load_no_trans: true
    show-sql: true
    hibernate:
      ddl-auto: update

# Server configuration
server:
  port: 8080