spring:
  kafka:
    producer:
      bootstrap-servers: localhost:29092

  data:
    mongodb:
      host: localhost
      port: 27017
      database: admin
      auditing:
        enabled: true
      auto-index-creation: true

  server:
    port: 8082